# Generated by Django 2.0 on 2020-07-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('chat_content', models.TextField(verbose_name='聊天内容')),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(verbose_name='产品价格')),
                ('user_address', models.CharField(max_length=128, verbose_name='收件人地址')),
                ('user_phone', models.CharField(max_length=32, verbose_name='收件人电话')),
                ('pay_way', models.PositiveIntegerField(choices=[(1, '线上支付'), (2, '货到付款')], default=1, verbose_name='支付方式')),
                ('user_name', models.CharField(max_length=32, verbose_name='收件人姓名')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='产品名')),
                ('price', models.FloatField(verbose_name='产品价格')),
                ('count', models.IntegerField(verbose_name='产品数量')),
                ('product_state', models.TextField(verbose_name='产品描述')),
                ('category', models.CharField(choices=[(3, 'fruit'), (4, 'vegetable')], default=3, max_length=32, verbose_name='商品类别')),
                ('product_address', models.CharField(max_length=128, verbose_name='生产地')),
                ('product_phone', models.CharField(max_length=32, verbose_name='联系电话')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='product_img')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='店铺名')),
                ('store_state', models.TextField(verbose_name='店铺描述')),
                ('store_address', models.CharField(max_length=128, verbose_name='店铺地址')),
                ('store_phone', models.CharField(max_length=128, verbose_name='店铺电话')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.store')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ManyToManyField(to='user.product_image', verbose_name='产品图片'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.store'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(to='user.product', verbose_name='订单对应的产品'),
        ),
        migrations.AddField(
            model_name='chat',
            name='send_user',
            field=models.ManyToManyField(to='user.User', verbose_name='发送者'),
        ),
    ]
