# Generated by Django 2.0 on 2020-08-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0.0, verbose_name='订单价格'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ShopCar', verbose_name='订单对应的产品'),
        ),
        migrations.AddField(
            model_name='product',
            name='Shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.ShopCar', verbose_name='购物车商品'),
        ),
    ]
