# Generated by Django 2.0 on 2020-08-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200802_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.ShopCar', verbose_name='购物车商品'),
        ),
    ]
